# Generated by Django 4.2.13 on 2026-07-20 19:48

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон номер')),
                ('role', models.CharField(choices=[('user', 'Пайдаланыўшы'), ('manager', 'Менеджер'), ('admin', 'Админ')], default='user', max_length=10, verbose_name='Роль')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Мекан-жайы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дизимнен өткен ўақты')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пайдаланыўшы',
                'verbose_name_plural': 'Пайдаланыўшылар',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты-жөни')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('message', models.TextField(verbose_name='Хабар')),
                ('is_read', models.BooleanField(default=False, verbose_name='Оқылды')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жиберилген ўақты')),
            ],
            options={
                'verbose_name': 'Байланыс хабары',
                'verbose_name_plural': 'Байланыс хабарлары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_kk', models.CharField(max_length=200, verbose_name='Аты (КҚ)')),
                ('description_kk', models.TextField(verbose_name='Баянлама (КҚ)')),
                ('category', models.CharField(choices=[('panel', 'Күн панели'), ('battery', 'Батарея'), ('inverter', 'Инвертор'), ('kit', 'Толық жынаят'), ('other', 'Басқа')], default='panel', max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Баҳасы (сум)')),
                ('power_kw', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Қуўаты (кВт)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Сүрет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Жарамлы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Қосылған ўақты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өзгертилген ўақты')),
            ],
            options={
                'verbose_name': 'Өним',
                'verbose_name_plural': 'Өнимлер',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Саны')),
                ('status', models.CharField(choices=[('new', 'Жаңа'), ('accepted', 'Қабыл алынды'), ('contacted', 'Клиент пенен байланысылды'), ('scheduled', 'Монтаж белгиленди'), ('installing', 'Орнатылмақта'), ('completed', 'Жуўмақланды'), ('cancelled', 'Бийкар етилди')], default='new', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ескертпелер')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='Менеджер ескертпеси')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Орнатыў мекан-жайы')),
                ('total_price', models.DecimalField(blank=True, decimal_places=0, max_digits=14, null=True, verbose_name='Жәми баҳасы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жасалған ўақты')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Өзгертилген ўақты')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.product', verbose_name='Өним')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пайдаланыўшы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказлар',
                'ordering': ['-created_at'],
            },
        ),
    ]
